services:
  mysql:
    image: mysql:8.0.36                # Use MySQL 8.0.36 official image
    container_name: mysql_container    # Container name
    environment:
      MYSQL_ROOT_PASSWORD: root        # Set root password
    ports:
      - "3316:3306"                    # Map host port 3307 â†’ container port 3306
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d  # Mount your SQL init folder
      - mysql_data:/var/lib/mysql             # Persistent database data

volumes:
  mysql_data:                           # Named volume for persistence
